#!/usr/bin/env python
# -*- coding: utf-8 -*-

import optparse
import sys

parser = optparse.OptionParser(usage="%prog -[ [d|1|v|o] -[debug|turn-on|verbose|output] ]", version="%prog 1.0")

##############################################################################
##############################################################################
##############################################################################

#
# on/off options
# ##############

#
# -d, --debug
#
parser.add_option( '-d', '--debug',
	dest    = "debug",
	default = False,
	action  = "store_true",
	help    = "Active Debug mode."
)
#
# -1, --turn-on
#
parser.add_option('-1', '--turn-on',
	dest    = "onOff",
	default = False,
	action  = "store_true",
	help    = "Enable inner flags"
)
#
# -v, --verbose
#
parser.add_option('-v', '--verbose',
	dest    = "verbose",
	default = False,
	action  = "store_true",
	help    = "Active verbose mode"
)

##############################################################################
# ----------------------------------------------------------------------------
##############################################################################

#
# Set options
# ###########
#

#
# -o, --output
#
parser.add_option('-o', '--output',
	dest    = "output_dest",
	default = "a.out",
	help    = "Define stdout FILE"
)

##############################################################################
##############################################################################
##############################################################################
options, remainder = parser.parse_args()
##############################################################################

if options.debug == True :
	#
	# OnOff - options
	#
	print ('DEBUG    :', options.debug)
	print ('ARGV     :', sys.argv[1:])
	print ('VERBOSE  :', options.verbose)
	print ('TURN ON  :', options.onOff)

	print ('OUTPUT   :', options.output_dest)


